# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: fr

# Change to your timezone
timezone: Africa/Porto-Novo

# jekyll-seo-tag settings
# ↓ --------------------------

title: xxa.nael

tagline: Web exploitation enthusiast

description: >-
  Blog de cybersécurité, Write-ups CTF (OSINT, Web, Forensics, Reverse) et fiches techniques.

url: "https://xxanael.github.io"

github:
  username: xxanael

social:
  name: xxanael
  email: donasingbo332@gmail.com
  links:
    - https://github.com/xxanael
    - https://www.linkedin.com/in/dona-marie-fid%C3%A8le-ana%C3%ABl-singbo-56526a3a6/

# Web Analytics Settings
analytics:
  google:
    id:

pageviews:
  provider:

# Force le thème sombre par défaut
theme_mode: dark

cdn:

# Avatar de la barre latérale
avatar: "/assets/img/avatar.jpg"

social_preview_image:

toc: true

actions:
  edit_post:
    enabled: false
    url: ""
    static_url: false

comments:
  provider:

assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

paginate: 10

# Chemin de votre dépôt GitHub Pages
url: "https://xxanael.github.io"
baseurl: "/xxanael-vlog"

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
    
favicon:
  path: "/assets/img/favicons"
